name: NuGet Publish

on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.0' # Change to your desired .NET version

      - name: Build and Pack
        run: dotnet build LogsByBrady.csproj --configuration Release && dotnet pack LogsByBrady.csproj --configuration Release --output ./artifacts

      - name: Publish to NuGet
        uses: nuget/nuget@v1
        with:
          command: push
          packages: ./artifacts/*.nupkg
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
          source: https://api.nuget.org/v3/index.json
